version: "3.8"
services:
    server:
        image: dl-server
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - ${ROOT_DIR}:/server
            - ${MODEL_DIR}:/.torch/iopath_cache/detectron2
        deploy:
            resources:
                reservations:
                    devices:
                    - capabilities: [gpu]
        command:
            [
                "python",
                "app.py"
            ]
